// Generated by scripts/sync-idl.mjs from the program build. Do not edit.
export type RewardFloat = {
  "address": "DYAhSCwm3zAdB5Li9wKxJknjgvN7SkQpQMRhpNoJdJJJ",
  "metadata": {
    "name": "rewardFloat",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Micro-loans to DePIN operators against future token rewards"
  },
  "instructions": [
    {
      "name": "borrow",
      "discriminator": [
        228,
        253,
        131,
        202,
        207,
        116,
        89,
        18
      ],
      "accounts": [
        {
          "name": "operator",
          "writable": true,
          "signer": true
        },
        {
          "name": "pool",
          "writable": true
        },
        {
          "name": "operatorAccount",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  111,
                  112,
                  101,
                  114,
                  97,
                  116,
                  111,
                  114
                ]
              },
              {
                "kind": "account",
                "path": "operator"
              }
            ]
          }
        },
        {
          "name": "loan",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  111,
                  97,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "operator"
              },
              {
                "kind": "arg",
                "path": "nonce"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "relations": [
            "pool"
          ]
        },
        {
          "name": "destination",
          "writable": true
        },
        {
          "name": "rewardMint"
        },
        {
          "name": "rewardAccount",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "account",
                "path": "operator"
              },
              {
                "kind": "const",
                "value": [
                  6,
                  221,
                  246,
                  225,
                  215,
                  101,
                  161,
                  147,
                  217,
                  203,
                  225,
                  70,
                  206,
                  235,
                  121,
                  172,
                  28,
                  180,
                  133,
                  237,
                  95,
                  91,
                  55,
                  145,
                  58,
                  140,
                  245,
                  133,
                  126,
                  255,
                  0,
                  169
                ]
              },
              {
                "kind": "account",
                "path": "rewardMint"
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89
              ]
            }
          }
        },
        {
          "name": "instructions",
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "nonce",
          "type": "u64"
        },
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "termPeriods",
          "type": "u8"
        },
        {
          "name": "sweepBps",
          "type": "u16"
        },
        {
          "name": "maxAprBps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "deposit",
      "discriminator": [
        242,
        35,
        198,
        137,
        82,
        225,
        242,
        182
      ],
      "accounts": [
        {
          "name": "lender",
          "writable": true,
          "signer": true
        },
        {
          "name": "pool",
          "writable": true
        },
        {
          "name": "lenderShare",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  104,
                  97,
                  114,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "pool"
              },
              {
                "kind": "account",
                "path": "lender"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "relations": [
            "pool"
          ]
        },
        {
          "name": "source",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "initializePool",
      "discriminator": [
        95,
        180,
        10,
        172,
        84,
        174,
        232,
        40
      ],
      "accounts": [
        {
          "name": "authority",
          "docs": [
            "Becomes the pool authority, the key that may later replace the attestor."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "pool",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  111,
                  111,
                  108
                ]
              },
              {
                "kind": "account",
                "path": "stableMint"
              }
            ]
          }
        },
        {
          "name": "stableMint",
          "docs": [
            "The stablecoin loans are issued and repaid in."
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "pool"
              }
            ]
          }
        },
        {
          "name": "programData",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  186,
                  72,
                  54,
                  121,
                  234,
                  58,
                  246,
                  21,
                  231,
                  195,
                  95,
                  203,
                  35,
                  30,
                  157,
                  66,
                  241,
                  250,
                  206,
                  69,
                  57,
                  56,
                  27,
                  89,
                  37,
                  243,
                  77,
                  216,
                  16,
                  254,
                  50,
                  127
                ]
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                2,
                168,
                246,
                145,
                78,
                136,
                161,
                176,
                226,
                16,
                21,
                62,
                247,
                99,
                174,
                43,
                0,
                194,
                185,
                61,
                22,
                193,
                36,
                210,
                192,
                83,
                122,
                16,
                4,
                128,
                0,
                0
              ]
            }
          }
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "attestor",
          "type": "pubkey"
        },
        {
          "name": "baseAprBps",
          "type": "u16"
        },
        {
          "name": "slopeAprBps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "repay",
      "discriminator": [
        234,
        103,
        67,
        82,
        208,
        234,
        219,
        166
      ],
      "accounts": [
        {
          "name": "payer",
          "signer": true
        },
        {
          "name": "pool",
          "writable": true,
          "relations": [
            "loan"
          ]
        },
        {
          "name": "loan",
          "writable": true
        },
        {
          "name": "operatorAccount",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  111,
                  112,
                  101,
                  114,
                  97,
                  116,
                  111,
                  114
                ]
              },
              {
                "kind": "account",
                "path": "loan.operator",
                "account": "loan"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "relations": [
            "pool"
          ]
        },
        {
          "name": "source",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "maxAmount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "setAttestor",
      "discriminator": [
        95,
        11,
        236,
        157,
        234,
        146,
        163,
        237
      ],
      "accounts": [
        {
          "name": "authority",
          "signer": true,
          "relations": [
            "pool"
          ]
        },
        {
          "name": "pool",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "attestor",
          "type": "pubkey"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "lenderShare",
      "discriminator": [
        241,
        123,
        149,
        50,
        141,
        224,
        21,
        42
      ]
    },
    {
      "name": "loan",
      "discriminator": [
        20,
        195,
        70,
        117,
        165,
        227,
        182,
        1
      ]
    },
    {
      "name": "operatorAccount",
      "discriminator": [
        65,
        8,
        134,
        32,
        87,
        254,
        91,
        212
      ]
    },
    {
      "name": "pool",
      "discriminator": [
        241,
        154,
        109,
        4,
        17,
        177,
        109,
        188
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "mathOverflow",
      "msg": "arithmetic overflow"
    },
    {
      "code": 6001,
      "name": "attestationNonceTooOld",
      "msg": "attestation nonce is older than the replay window and can no longer be checked"
    },
    {
      "code": 6002,
      "name": "attestationNonceAlreadyUsed",
      "msg": "attestation nonce was already used"
    },
    {
      "code": 6003,
      "name": "notUpgradeAuthority",
      "msg": "only the upgrade authority of this program can create a pool"
    },
    {
      "code": 6004,
      "name": "notPoolAuthority",
      "msg": "only the pool authority can replace the attestor"
    },
    {
      "code": 6005,
      "name": "invalidAttestor",
      "msg": "the attestor key cannot be the all-zero key"
    },
    {
      "code": 6006,
      "name": "attestationMissing",
      "msg": "borrow must come right after the ed25519 checks of the rate and then the limit attestation"
    },
    {
      "code": 6007,
      "name": "attestationMalformed",
      "msg": "an attestation or its ed25519 check is not laid out as expected"
    },
    {
      "code": 6008,
      "name": "attestationWrongSigner",
      "msg": "an attestation is not signed by the pool attestor"
    },
    {
      "code": 6009,
      "name": "attestationWrongOperator",
      "msg": "the limit attestation was issued for another operator"
    },
    {
      "code": 6010,
      "name": "attestationExpired",
      "msg": "the limit attestation has expired"
    },
    {
      "code": 6011,
      "name": "attestationValidityTooLong",
      "msg": "the limit attestation claims to stay valid for longer than the program allows"
    },
    {
      "code": 6012,
      "name": "attestationStale",
      "msg": "the limit attestation was computed from data older than a day"
    },
    {
      "code": 6013,
      "name": "invalidRateCurve",
      "msg": "the base rate plus the utilisation premium must fit in u16 basis points"
    },
    {
      "code": 6014,
      "name": "invalidAmount",
      "msg": "the amount must be greater than zero"
    },
    {
      "code": 6015,
      "name": "invalidTerm",
      "msg": "the loan term must be between one and the maximum number of periods"
    },
    {
      "code": 6016,
      "name": "invalidSweepShare",
      "msg": "the share of rewards withheld must be between 1 and 10000 basis points"
    },
    {
      "code": 6017,
      "name": "operatorOverdue",
      "msg": "an operator with an overdue loan cannot borrow"
    },
    {
      "code": 6018,
      "name": "creditLimitExceeded",
      "msg": "the loan would take the operator's debt over the attested credit limit"
    },
    {
      "code": 6019,
      "name": "insufficientLiquidity",
      "msg": "the pool does not have enough free liquidity for this loan"
    },
    {
      "code": 6020,
      "name": "rateAboveMaximum",
      "msg": "the rate for this loan is above the maximum the operator agreed to"
    },
    {
      "code": 6021,
      "name": "attestationNonceMismatch",
      "msg": "the loan nonce is not the nonce of the limit attestation"
    },
    {
      "code": 6022,
      "name": "loanNotOpen",
      "msg": "the loan is already repaid"
    },
    {
      "code": 6023,
      "name": "openLoansMismatch",
      "msg": "every open loan of the operator in this pool has to be passed, writable and once"
    },
    {
      "code": 6024,
      "name": "tooManyOpenLoans",
      "msg": "the operator already has the maximum number of open loans"
    },
    {
      "code": 6025,
      "name": "depositTooSmall",
      "msg": "the deposit is worth less than one share of the pool"
    },
    {
      "code": 6026,
      "name": "rateAttestationWrongMint",
      "msg": "the rate attestation is for another reward token than the loan's"
    },
    {
      "code": 6027,
      "name": "rateAttestationExpired",
      "msg": "the rate attestation has expired"
    },
    {
      "code": 6028,
      "name": "rateAttestationValidityTooLong",
      "msg": "the rate attestation claims to stay valid for longer than the program allows"
    },
    {
      "code": 6029,
      "name": "rateAttestationStale",
      "msg": "the rate attestation was priced more than ten minutes ago"
    },
    {
      "code": 6030,
      "name": "delegationTooSmall",
      "msg": "at the attested rate the debt is worth less than one base unit of the reward token"
    }
  ],
  "types": [
    {
      "name": "lenderShare",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "pool",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "shares",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "loan",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "operator",
            "type": "pubkey"
          },
          {
            "name": "pool",
            "type": "pubkey"
          },
          {
            "name": "rewardMint",
            "type": "pubkey"
          },
          {
            "name": "nonce",
            "type": "u64"
          },
          {
            "name": "principal",
            "type": "u64"
          },
          {
            "name": "outstanding",
            "type": "u64"
          },
          {
            "name": "accruedInterest",
            "type": "u64"
          },
          {
            "name": "interestRemainder",
            "type": "u64"
          },
          {
            "name": "openedAt",
            "type": "i64"
          },
          {
            "name": "dueAt",
            "type": "i64"
          },
          {
            "name": "lastAccrualAt",
            "type": "i64"
          },
          {
            "name": "aprBps",
            "type": "u16"
          },
          {
            "name": "sweepBps",
            "type": "u16"
          },
          {
            "name": "status",
            "type": {
              "defined": {
                "name": "loanStatus"
              }
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "loanStatus",
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "active"
          },
          {
            "name": "overdue"
          },
          {
            "name": "repaid"
          }
        ]
      }
    },
    {
      "name": "operatorAccount",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "totalDebt",
            "type": "u64"
          },
          {
            "name": "openLoans",
            "type": "u32"
          },
          {
            "name": "overdue",
            "type": "bool"
          },
          {
            "name": "nonceFloor",
            "type": "u64"
          },
          {
            "name": "usedNonces",
            "type": {
              "array": [
                "u64",
                4
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "pool",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "authority",
            "type": "pubkey"
          },
          {
            "name": "attestor",
            "type": "pubkey"
          },
          {
            "name": "stableMint",
            "type": "pubkey"
          },
          {
            "name": "vault",
            "type": "pubkey"
          },
          {
            "name": "totalShares",
            "type": "u64"
          },
          {
            "name": "totalDeposits",
            "type": "u64"
          },
          {
            "name": "totalBorrowed",
            "type": "u64"
          },
          {
            "name": "accruedInterest",
            "type": "u64"
          },
          {
            "name": "accrualRate",
            "type": "u128"
          },
          {
            "name": "accrualRateTime",
            "type": "u128"
          },
          {
            "name": "accrualRemainders",
            "type": "u128"
          },
          {
            "name": "overduePrincipal",
            "type": "u64"
          },
          {
            "name": "baseAprBps",
            "type": "u16"
          },
          {
            "name": "slopeAprBps",
            "type": "u16"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    }
  ]
}

export const rewardFloatIdl: RewardFloat = {
  "address": "DYAhSCwm3zAdB5Li9wKxJknjgvN7SkQpQMRhpNoJdJJJ",
  "metadata": {
    "name": "rewardFloat",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Micro-loans to DePIN operators against future token rewards"
  },
  "instructions": [
    {
      "name": "borrow",
      "discriminator": [
        228,
        253,
        131,
        202,
        207,
        116,
        89,
        18
      ],
      "accounts": [
        {
          "name": "operator",
          "writable": true,
          "signer": true
        },
        {
          "name": "pool",
          "writable": true
        },
        {
          "name": "operatorAccount",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  111,
                  112,
                  101,
                  114,
                  97,
                  116,
                  111,
                  114
                ]
              },
              {
                "kind": "account",
                "path": "operator"
              }
            ]
          }
        },
        {
          "name": "loan",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  108,
                  111,
                  97,
                  110
                ]
              },
              {
                "kind": "account",
                "path": "operator"
              },
              {
                "kind": "arg",
                "path": "nonce"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "relations": [
            "pool"
          ]
        },
        {
          "name": "destination",
          "writable": true
        },
        {
          "name": "rewardMint"
        },
        {
          "name": "rewardAccount",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "account",
                "path": "operator"
              },
              {
                "kind": "const",
                "value": [
                  6,
                  221,
                  246,
                  225,
                  215,
                  101,
                  161,
                  147,
                  217,
                  203,
                  225,
                  70,
                  206,
                  235,
                  121,
                  172,
                  28,
                  180,
                  133,
                  237,
                  95,
                  91,
                  55,
                  145,
                  58,
                  140,
                  245,
                  133,
                  126,
                  255,
                  0,
                  169
                ]
              },
              {
                "kind": "account",
                "path": "rewardMint"
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89
              ]
            }
          }
        },
        {
          "name": "instructions",
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "nonce",
          "type": "u64"
        },
        {
          "name": "amount",
          "type": "u64"
        },
        {
          "name": "termPeriods",
          "type": "u8"
        },
        {
          "name": "sweepBps",
          "type": "u16"
        },
        {
          "name": "maxAprBps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "deposit",
      "discriminator": [
        242,
        35,
        198,
        137,
        82,
        225,
        242,
        182
      ],
      "accounts": [
        {
          "name": "lender",
          "writable": true,
          "signer": true
        },
        {
          "name": "pool",
          "writable": true
        },
        {
          "name": "lenderShare",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  115,
                  104,
                  97,
                  114,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "pool"
              },
              {
                "kind": "account",
                "path": "lender"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "relations": [
            "pool"
          ]
        },
        {
          "name": "source",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "initializePool",
      "discriminator": [
        95,
        180,
        10,
        172,
        84,
        174,
        232,
        40
      ],
      "accounts": [
        {
          "name": "authority",
          "docs": [
            "Becomes the pool authority, the key that may later replace the attestor."
          ],
          "writable": true,
          "signer": true
        },
        {
          "name": "pool",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  112,
                  111,
                  111,
                  108
                ]
              },
              {
                "kind": "account",
                "path": "stableMint"
              }
            ]
          }
        },
        {
          "name": "stableMint",
          "docs": [
            "The stablecoin loans are issued and repaid in."
          ]
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "pool"
              }
            ]
          }
        },
        {
          "name": "programData",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  186,
                  72,
                  54,
                  121,
                  234,
                  58,
                  246,
                  21,
                  231,
                  195,
                  95,
                  203,
                  35,
                  30,
                  157,
                  66,
                  241,
                  250,
                  206,
                  69,
                  57,
                  56,
                  27,
                  89,
                  37,
                  243,
                  77,
                  216,
                  16,
                  254,
                  50,
                  127
                ]
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                2,
                168,
                246,
                145,
                78,
                136,
                161,
                176,
                226,
                16,
                21,
                62,
                247,
                99,
                174,
                43,
                0,
                194,
                185,
                61,
                22,
                193,
                36,
                210,
                192,
                83,
                122,
                16,
                4,
                128,
                0,
                0
              ]
            }
          }
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "systemProgram",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "attestor",
          "type": "pubkey"
        },
        {
          "name": "baseAprBps",
          "type": "u16"
        },
        {
          "name": "slopeAprBps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "repay",
      "discriminator": [
        234,
        103,
        67,
        82,
        208,
        234,
        219,
        166
      ],
      "accounts": [
        {
          "name": "payer",
          "signer": true
        },
        {
          "name": "pool",
          "writable": true,
          "relations": [
            "loan"
          ]
        },
        {
          "name": "loan",
          "writable": true
        },
        {
          "name": "operatorAccount",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  111,
                  112,
                  101,
                  114,
                  97,
                  116,
                  111,
                  114
                ]
              },
              {
                "kind": "account",
                "path": "loan.operator",
                "account": "loan"
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "relations": [
            "pool"
          ]
        },
        {
          "name": "source",
          "writable": true
        },
        {
          "name": "tokenProgram",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "maxAmount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "setAttestor",
      "discriminator": [
        95,
        11,
        236,
        157,
        234,
        146,
        163,
        237
      ],
      "accounts": [
        {
          "name": "authority",
          "signer": true,
          "relations": [
            "pool"
          ]
        },
        {
          "name": "pool",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "attestor",
          "type": "pubkey"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "lenderShare",
      "discriminator": [
        241,
        123,
        149,
        50,
        141,
        224,
        21,
        42
      ]
    },
    {
      "name": "loan",
      "discriminator": [
        20,
        195,
        70,
        117,
        165,
        227,
        182,
        1
      ]
    },
    {
      "name": "operatorAccount",
      "discriminator": [
        65,
        8,
        134,
        32,
        87,
        254,
        91,
        212
      ]
    },
    {
      "name": "pool",
      "discriminator": [
        241,
        154,
        109,
        4,
        17,
        177,
        109,
        188
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "mathOverflow",
      "msg": "arithmetic overflow"
    },
    {
      "code": 6001,
      "name": "attestationNonceTooOld",
      "msg": "attestation nonce is older than the replay window and can no longer be checked"
    },
    {
      "code": 6002,
      "name": "attestationNonceAlreadyUsed",
      "msg": "attestation nonce was already used"
    },
    {
      "code": 6003,
      "name": "notUpgradeAuthority",
      "msg": "only the upgrade authority of this program can create a pool"
    },
    {
      "code": 6004,
      "name": "notPoolAuthority",
      "msg": "only the pool authority can replace the attestor"
    },
    {
      "code": 6005,
      "name": "invalidAttestor",
      "msg": "the attestor key cannot be the all-zero key"
    },
    {
      "code": 6006,
      "name": "attestationMissing",
      "msg": "borrow must come right after the ed25519 checks of the rate and then the limit attestation"
    },
    {
      "code": 6007,
      "name": "attestationMalformed",
      "msg": "an attestation or its ed25519 check is not laid out as expected"
    },
    {
      "code": 6008,
      "name": "attestationWrongSigner",
      "msg": "an attestation is not signed by the pool attestor"
    },
    {
      "code": 6009,
      "name": "attestationWrongOperator",
      "msg": "the limit attestation was issued for another operator"
    },
    {
      "code": 6010,
      "name": "attestationExpired",
      "msg": "the limit attestation has expired"
    },
    {
      "code": 6011,
      "name": "attestationValidityTooLong",
      "msg": "the limit attestation claims to stay valid for longer than the program allows"
    },
    {
      "code": 6012,
      "name": "attestationStale",
      "msg": "the limit attestation was computed from data older than a day"
    },
    {
      "code": 6013,
      "name": "invalidRateCurve",
      "msg": "the base rate plus the utilisation premium must fit in u16 basis points"
    },
    {
      "code": 6014,
      "name": "invalidAmount",
      "msg": "the amount must be greater than zero"
    },
    {
      "code": 6015,
      "name": "invalidTerm",
      "msg": "the loan term must be between one and the maximum number of periods"
    },
    {
      "code": 6016,
      "name": "invalidSweepShare",
      "msg": "the share of rewards withheld must be between 1 and 10000 basis points"
    },
    {
      "code": 6017,
      "name": "operatorOverdue",
      "msg": "an operator with an overdue loan cannot borrow"
    },
    {
      "code": 6018,
      "name": "creditLimitExceeded",
      "msg": "the loan would take the operator's debt over the attested credit limit"
    },
    {
      "code": 6019,
      "name": "insufficientLiquidity",
      "msg": "the pool does not have enough free liquidity for this loan"
    },
    {
      "code": 6020,
      "name": "rateAboveMaximum",
      "msg": "the rate for this loan is above the maximum the operator agreed to"
    },
    {
      "code": 6021,
      "name": "attestationNonceMismatch",
      "msg": "the loan nonce is not the nonce of the limit attestation"
    },
    {
      "code": 6022,
      "name": "loanNotOpen",
      "msg": "the loan is already repaid"
    },
    {
      "code": 6023,
      "name": "openLoansMismatch",
      "msg": "every open loan of the operator in this pool has to be passed, writable and once"
    },
    {
      "code": 6024,
      "name": "tooManyOpenLoans",
      "msg": "the operator already has the maximum number of open loans"
    },
    {
      "code": 6025,
      "name": "depositTooSmall",
      "msg": "the deposit is worth less than one share of the pool"
    },
    {
      "code": 6026,
      "name": "rateAttestationWrongMint",
      "msg": "the rate attestation is for another reward token than the loan's"
    },
    {
      "code": 6027,
      "name": "rateAttestationExpired",
      "msg": "the rate attestation has expired"
    },
    {
      "code": 6028,
      "name": "rateAttestationValidityTooLong",
      "msg": "the rate attestation claims to stay valid for longer than the program allows"
    },
    {
      "code": 6029,
      "name": "rateAttestationStale",
      "msg": "the rate attestation was priced more than ten minutes ago"
    },
    {
      "code": 6030,
      "name": "delegationTooSmall",
      "msg": "at the attested rate the debt is worth less than one base unit of the reward token"
    }
  ],
  "types": [
    {
      "name": "lenderShare",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "pool",
            "type": "pubkey"
          },
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "shares",
            "type": "u64"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "loan",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "operator",
            "type": "pubkey"
          },
          {
            "name": "pool",
            "type": "pubkey"
          },
          {
            "name": "rewardMint",
            "type": "pubkey"
          },
          {
            "name": "nonce",
            "type": "u64"
          },
          {
            "name": "principal",
            "type": "u64"
          },
          {
            "name": "outstanding",
            "type": "u64"
          },
          {
            "name": "accruedInterest",
            "type": "u64"
          },
          {
            "name": "interestRemainder",
            "type": "u64"
          },
          {
            "name": "openedAt",
            "type": "i64"
          },
          {
            "name": "dueAt",
            "type": "i64"
          },
          {
            "name": "lastAccrualAt",
            "type": "i64"
          },
          {
            "name": "aprBps",
            "type": "u16"
          },
          {
            "name": "sweepBps",
            "type": "u16"
          },
          {
            "name": "status",
            "type": {
              "defined": {
                "name": "loanStatus"
              }
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "loanStatus",
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "active"
          },
          {
            "name": "overdue"
          },
          {
            "name": "repaid"
          }
        ]
      }
    },
    {
      "name": "operatorAccount",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "totalDebt",
            "type": "u64"
          },
          {
            "name": "openLoans",
            "type": "u32"
          },
          {
            "name": "overdue",
            "type": "bool"
          },
          {
            "name": "nonceFloor",
            "type": "u64"
          },
          {
            "name": "usedNonces",
            "type": {
              "array": [
                "u64",
                4
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "pool",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "authority",
            "type": "pubkey"
          },
          {
            "name": "attestor",
            "type": "pubkey"
          },
          {
            "name": "stableMint",
            "type": "pubkey"
          },
          {
            "name": "vault",
            "type": "pubkey"
          },
          {
            "name": "totalShares",
            "type": "u64"
          },
          {
            "name": "totalDeposits",
            "type": "u64"
          },
          {
            "name": "totalBorrowed",
            "type": "u64"
          },
          {
            "name": "accruedInterest",
            "type": "u64"
          },
          {
            "name": "accrualRate",
            "type": "u128"
          },
          {
            "name": "accrualRateTime",
            "type": "u128"
          },
          {
            "name": "accrualRemainders",
            "type": "u128"
          },
          {
            "name": "overduePrincipal",
            "type": "u64"
          },
          {
            "name": "baseAprBps",
            "type": "u16"
          },
          {
            "name": "slopeAprBps",
            "type": "u16"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    }
  ]
}
