// Copies the program interface from the Anchor build into @drf/anchor-client.
//   node scripts/sync-idl.mjs          write the vendored files
//   node scripts/sync-idl.mjs --check  fail if they differ from the build
//
// target/ is not in git and `anchor build` only runs in WSL, while api, worker and web
// are built where neither exists, so the client carries its own copy. The check is how
// a program change that was never synced stops a commit instead of shipping a client
// that encodes the old instructions.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const builtIdl = join(root, 'target/idl/reward_float.json')
const builtTypes = join(root, 'target/types/reward_float.ts')
const vendored = join(root, 'packages/anchor-client/src/idl')
const TYPE_PREFIX = 'export type RewardFloat = '

function expectedFiles() {
  const types = readFileSync(builtTypes, 'utf8').replace(/\r\n/g, '\n')
  const at = types.indexOf(TYPE_PREFIX)
  if (at === -1) throw new Error(`${builtTypes} does not declare RewardFloat`)
  // The camelCase body is both the type and the value: Program converts whatever it is
  // given to camelCase, so a value built from the raw snake_case JSON would not be
  // assignable to the generated type (args paths in PDA seeds keep their snake_case).
  const body = types.slice(at + TYPE_PREFIX.length).trim().replace(/;$/, '')
  JSON.parse(body)

  const module = [
    '// Generated by scripts/sync-idl.mjs from the program build. Do not edit.',
    `${TYPE_PREFIX}${body}`,
    '',
    `export const rewardFloatIdl: RewardFloat = ${body}`,
    '',
  ].join('\n')

  return new Map([
    ['reward_float.json', readFileSync(builtIdl, 'utf8').replace(/\r\n/g, '\n')],
    ['reward-float.ts', module],
  ])
}

const check = process.argv.includes('--check')

if (!existsSync(builtIdl) || !existsSync(builtTypes)) {
  if (!check) {
    console.error('no program build in target/: run scripts/wsl-build.sh first')
    process.exit(1)
  }
  console.log('idl check skipped: no program build in target/')
  process.exit(0)
}

const stale = []
if (!check) mkdirSync(vendored, { recursive: true })
for (const [name, contents] of expectedFiles()) {
  const path = join(vendored, name)
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== contents) stale.push(name)
  } else {
    writeFileSync(path, contents)
  }
}

if (stale.length > 0) {
  console.error(`vendored IDL differs from target/: ${stale.join(', ')} — run pnpm idl:sync`)
  process.exit(1)
}
console.log(check ? 'vendored IDL matches target/' : 'IDL synced into packages/anchor-client/src/idl')
